# Generated by Django 3.2.6 on 2021-08-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_noticia_denuncias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
