# Generated by Django 3.2.6 on 2021-08-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_publicacion',
        ),
    ]
