# Generated by Django 3.2.6 on 2021-08-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_remove_noticia_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.CharField(choices=[('publicada', 'Noticia publicada en el sitio'), ('borrador', 'Noticia todavía siendo escrita'), ('en_revision', 'Noticia siendo revisada')], default='borrador', max_length=50),
        ),
    ]
